{% set name = "montydb" %}
{% set version = "2.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/montydb-{{ version }}.tar.gz
  sha256: e19386ccaed146103292b9a92fad6803d0561182aa074c34ddf08b21df28b103

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - montydb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/davidlatwe/montydb
  summary: Monty, Mongo tinified. MongoDB implemented in Python !
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
