{% set name = "montydb" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/montydb-{{ version }}.tar.gz
  sha256: b9857e3fec14fedaa48f0fd14004b8b4b9486ff0612cf055f778bfb50a03d774

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<3.11
  run:
    - python >=3.6,<3.11

test:
  imports:
    - montydb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davidlatwe/montydb
  summary: Monty, Mongo tinified. MongoDB implemented in Python !
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
