{% set name = "montydb" %}
{% set version = "2.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/montydb-{{ version }}.tar.gz
  sha256: 10591b5c4e1b44d01faa18c5c001a4c738af52fdf8cac04b744a17e352a743ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - montydb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davidlatwe/montydb
  summary: Monty, Mongo tinified. MongoDB implemented in Python !
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
