schema_version: 1

context:
  name: montydb
  version: "2.5.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/montydb-${{ version }}.tar.gz
  sha256: 1f7ac08f6af3822d9454d21eb20f1bfc935ecfa5af901fdeb1d265b171911618

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - montydb
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Monty, Mongo tinified. MongoDB implemented in Python !
  license: BSD-3-Clause
  license_file:
    - LICENSE
  homepage: https://github.com/davidlatwe/montydb

extra:
  recipe-maintainers:
    - thewchan
